AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Main template for serverless PyPi

Parameters:
  Stage:
    Type: String
    Description: Stage for deployment.
  Domain:
    Type: String
    Description: Domain used for API
  FunctionStackURL:
    Type: String
    Description: S3 Location for Function Stack
  ACMStackURL:
    Type: String
    Description: S3 Location for ACM Stack
  APIGWStackURL:
    Type: String
    Description: S3 Location for APIGW Stack

Resources:
 FunctionStack:
   Type: AWS::CloudFormation::Stack
   Properties:
     TemplateURL: !Ref FunctionStackURL

 ACMStack:
   Type: AWS::CloudFormation::Stack
   Properties:
     Parameters:
       Stage: !Ref Stage
       Domain: !Ref Domain
     TemplateURL: !Ref ACMStackURL

 APIGWStack:
   Type: AWS::CloudFormation::Stack
   Properties:
     Parameters:
       Stage: !Ref Stage
       Domain: !Ref Domain
       AuthorizerArn: !GetAtt FunctionStack.Outputs.AuthorizerFunctionArn
       JWTCreatorArn: !GetAtt FunctionStack.Outputs.JWTProviderFunctionArn
       PackageTableName: !GetAtt FunctionStack.Outputs.PackageTableName
       ACMCertArn: !GetAtt ACMStack.Outputs.ACMCertArn
       RedirectFunctionArn: !GetAtt FunctionStack.Outputs.RedirectFunctionArn
     TemplateURL: !Ref APIGWStackURL
