AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverlessPyPi

  Sample SAM Template for serverlessPyPi

Resources:
  ProcessUploadsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: process_uploads/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 300
      Policies:
        - Statement:
            - Effect: "Allow"
              Action: "*"
              Resource: "*"
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBTable
  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: redirect_function/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 300
      Policies:
        - Statement:
            - Effect: "Allow"
              Action: "*"
              Resource: "*"

  JWTProviderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: custom_auth/
      Handler: app.jwt_provider_handler
      Runtime: python3.7
      Timeout: 300
      Policies:
        - Statement:
            - Effect: "Allow"
              Action: "*"
              Resource: "*"
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref UserTokenTable

  AuthValidatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: custom_auth/
      Handler: app.custom_auth_handler
      Runtime: python3.7
      Timeout: 300
      Policies:
        - Statement:
            - Effect: "Allow"
              Action: "*"
              Resource: "*"
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref UserTokenTable

  PyPiBucket:
    Type: AWS::S3::Bucket


  UserTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TimeToLiveSpecification:
        AttributeName: "Expires"
        Enabled: true
      AttributeDefinitions:
        - AttributeName: "PartitionKey"
          AttributeType: "S"
        - AttributeName: "SortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PartitionKey"
          KeyType: "HASH"
        - AttributeName: "SortKey"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "PartitionKey"
          AttributeType: "S"
        - AttributeName: "SortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PartitionKey"
          KeyType: "HASH"
        - AttributeName: "SortKey"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  DDBTableName:
    Description: "Name for DynamoDB Table"
    Value: !Ref DDBTable
    Export:
      Name: PackageTable

  PyPiBucketName:
    Description: "Arn for redirect Function"
    Value: !Ref PyPiBucket
    Export:
      Name: PyPiBucketName

  AuthorizerFunctionArn:
    Description: "Arn for Authorizer Function"
    Value: !GetAtt AuthValidatorFunction.Arn
    Export:
      Name: AuthorizerFunctionArn

  JWTProviderFunctionArn:
    Description: "Arn for JWTProviderFunction"
    Value: !GetAtt JWTProviderFunction.Arn
    Export:
      Name: JWTProviderFunctionArn
