AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Stage for deployment.
  Domain:
    Type: String
    Description: Domain used for API

Resources:
    ACMRegisterFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ../functions/acm_register/
            Handler: app.lambda_handler
            Runtime: python3.7
            Timeout: 900
            Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - acm:*
                      - route53:*
                      - lambda:Invoke*
                    Resource: '*'
    ACMCertificate:
      Type: 'Custom::ACMCertificate'
      Version: '1.0'
      Properties:
        ServiceToken: !GetAtt ACMRegisterFunction.Arn
        Region: !Ref "AWS::Region"
        HostedZoneName: !Sub "${Stage}.${Domain}"

Outputs:
    ACMCertArn:
      Description: "ACM Certificate Arn"
      Value: !GetAtt ACMCertificate.Arn